export const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_URL || "http://localhost:8000/api",
  TIMEOUT: 30000,
  HEADERS: {
    "Content-Type": "application/json",
  },
};

export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login/",
    LOGOUT: "/auth/logout/",
    REFRESH: "/auth/refresh/",
    ME: "/users/me/",
  },
  DASHBOARD: {
    OVERVIEW: "/dashboard/overview/",
    ACTIVITY: "/dashboard/activity/",
    DOCUMENTS_STATS: "/dashboard/documents_stats/",
    FORMS_STATS: "/dashboard/forms_stats/",
    USERS_ACTIVITY: "/dashboard/users_activity/",
  },
  PATIENTS: {
    LIST: "/patients/",
    DETAIL: (id: string) => `/patients/${id}/`,
    CREATE: "/patients/",
    STATS: "/patients/stats/",
    CLINICAL_RECORDS: (id: string) => `/patients/${id}/clinical_records/`,
  },
  CLINICAL_RECORDS: {
    LIST: "/clinical-records/",
    DETAIL: (id: string) => `/clinical-records/${id}/`,
    CREATE: "/clinical-records/",
    DOCUMENTS: (id: string) => `/clinical-records/${id}/documents/`,
    TIMELINE: (id: string) => `/clinical-records/${id}/timeline/`,
    ARCHIVE: (id: string) => `/clinical-records/${id}/archive/`,
    CLOSE: (id: string) => `/clinical-records/${id}/close/`,
    FORMS: "/clinical-records/forms/",
    FORMS_BY_RECORD: (id: string) => `/clinical-records/forms/?clinical_record_id=${id}`,
    FORMS_BY_TYPE: (type: string) => `/clinical-records/forms/?form_type=${type}`,
    FORMS_TYPES: "/clinical-records/forms/form_types/",
  },
  DOCUMENTS: {
    LIST: "/documents/",
    DETAIL: (id: string) => `/documents/${id}/`,
    UPLOAD: "/documents/upload/",
    SEARCH: "/documents/search/",
    DOWNLOAD: (id: string) => `/documents/${id}/download/`,
    SIGN: (id: string) => `/documents/${id}/sign/`,
    ACCESS_LOG: (id: string) => `/documents/${id}/access_log/`,
  },
  AUDIT: {
    LIST: "/audit/",
    DETAIL: (id: string) => `/audit/${id}/`,
    VERIFY_INTEGRITY: (id: string) => `/audit/${id}/verify_integrity/`,
    STATS: "/audit/stats/",
    RECENT_SUSPICIOUS: "/audit/recent_suspicious/",
  },
  REPORTS: {
    GENERATE: "/reports/generator/generate/",
    GENERATE_DYNAMIC: "/reports/generator/generate_dynamic/",
    AVAILABLE_TYPES: "/reports/generator/available_types/",
    LIST: "/reports/executions/",
    DETAIL: (id: string) => `/reports/executions/${id}/`,
    DOWNLOAD: (id: string) => `/reports/executions/${id}/download/`,
    ANALYZE: (id: string) => `/reports/executions/${id}/analyze/`,
    SUMMARIZE: (id: string) => `/reports/executions/${id}/summarize/`,
    RECOMMENDATIONS: (id: string) => `/reports/executions/${id}/recommendations/`,
    AI_INSIGHTS: (id: string) => `/reports/executions/${id}/ai_insights/`,
    TEMPLATES: "/reports/templates/",
  },
  NOTIFICATIONS: {
    LIST: "/notifications/",
    DETAIL: (id: string) => `/notifications/${id}/`,
    MARK_AS_READ: (id: string) => `/notifications/${id}/read/`,
    MARK_ALL_AS_READ: "/notifications/mark_all_as_read/",
    UNREAD_COUNT: "/notifications/unread_count/",
    SEND: "/notifications/send/",
  },
  SEED: {
    GENERATE: "/seed/generate/",
    LIST: "/seed/list/",
  },
};
